In [2]:
import numpy as np
import pandas as pd
a=np.arange(15)
a[6:10]

array([6, 7, 8, 9])

In [3]:
a=np.arange(20).reshape(4,5)
a[[1,0,2,3],:]

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
a[:,[1,0,2,3]]

array([[ 1,  0,  2,  3],
       [ 6,  5,  7,  8],
       [11, 10, 12, 13],
       [16, 15, 17, 18]])

In [5]:
a=np.random.randint(1,10,size=(5,5))
a[np.where(a%2==1)]=0
a

array([[2, 0, 0, 0, 0],
       [2, 0, 0, 6, 0],
       [6, 0, 0, 0, 0],
       [8, 0, 0, 0, 0],
       [0, 8, 6, 6, 0]])

In [6]:
a=np.random.randint(1,10,size=(4,5))
a=a.ravel()
index=np.argsort(-a)[:5]
index

array([17, 10, 11, 13, 16], dtype=int64)

In [7]:
a

array([6, 6, 5, 3, 4, 3, 4, 6, 2, 2, 9, 9, 7, 9, 2, 8, 8, 9, 1, 2])

In [8]:
a[np.where(a>30)]=0
a.reshape(4,5)

array([[6, 6, 5, 3, 4],
       [3, 4, 6, 2, 2],
       [9, 9, 7, 9, 2],
       [8, 8, 9, 1, 2]])

In [9]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris_2d = np.genfromtxt(url,delimiter=',',dtype='float')
iris_2d[:5]

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan]])

In [10]:
np.random.seed(100)
i,j=np.where(iris_2d)
iris_2d[np.random.choice((i),20),np.random.choice((j),20)]=np.nan
iris_2d[:5]

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan]])

In [11]:
print(np.isnan(iris_2d[:,0]).sum())
print(np.where(np.isnan(iris_2d[:,0])))

3
(array([ 45,  56, 115], dtype=int64),)


In [12]:
b = (iris_2d[:,2]>1.5)&(iris_2d[:,0]<5.0)
iris_2d[b]

array([[4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [4.7, 3.2, 1.6, 0.2, nan],
       [4.8, 3.1, 1.6, 0.2, nan],
       [4.9, 2.4, 3.3, 1. , nan],
       [4.9, 2.5, 4.5, 1.7, nan]])

In [14]:
x=np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[x]

array([], shape=(0, 5), dtype=float64)

In [15]:
np.isnan(iris_2d).any()

True

In [16]:
iris_2d[np.where(np.isnan(iris_2d))]=0
iris_2d[:5]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])

In [18]:
a1=np.digitize(iris_2d[:,2],[0,3,5])
b={1:'小',2:'中',3:'大'}
for i in a1:
    print(b[i])

小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
小
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
大
中
中
中
中
中
大
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
中
大
小
大
大
大
大
中
大
大
大
大
大
大
大
小
大
大
大
大
大
大
中
大
中
大
大
中
中
大
大
大
小
大
大
大
大
大
大
中
大
大
大
大
大
大
大
大
大
大
大


In [19]:
petallength=iris_2d[:,2]
sepallength=iris_2d[:,0]
volume=(np.pi*petallength * (sepallength**2))/3
volume[:20]

array([38.13265163, 35.20049849, 30.07237208, 33.23805027, 36.65191429,
       51.91167701, 31.02218026, 39.26990817, 28.38324243, 37.71481981,
       45.80442089, 38.60389053, 33.77840421, 21.29895099, 42.27327075,
        0.        , 39.69716477, 38.13265163, 57.83986235, 40.85641246])

In [20]:
np.argmax(iris_2d[:,3]>1)

50

In [21]:
a=np.array([1,9,5,12,8,20,4,10,2,8])
b=np.array([5,12,8,20,4,10,2,8,1,9])
C=np.sqrt(np.sum(np.square(a-b)))
C

14.966629547095765